### ISSUE TITLE
Build failed on Cordova > 4

### ISSUE THREAD

**Issue by Piranya** [AllJoyn-Cordova/cordova-chat-alljoyn#4]
I have an error on build with initWithWebView. I've found similar issue https://github.com/shazron/KeychainPlugin/issues/21 and installing older (<4) version of cordova solves the problem.

Possible solution: initWithWebView goes away in cordova-ios 4.0, all plugin initialization should be in the pluginInitialize function.

**Comment by vjrantal** [comment]
Thanks for the issue report.

If this is a build issue you get after adding cordova-plugin-alljoyn, would it be too much to ask to report it under that repository: https://github.com/AllJoyn-Cordova/cordova-plugin-alljoyn.

**Comment by Piranya** [comment]
Posted an issue there.

**Comment by vjrantal** [comment]
@Piranya: Thanks!
